# Usamos la imagen base oficial de Node.js
FROM node:16

# Establecemos el directorio de trabajo
WORKDIR /app

# Instalar dependencias globales
RUN npm install -g express

# Definir un comando por defecto (opcional)
CMD ["node", "index.js"]
