name: Build and Push Docker Image

on:
  push:
    branches:
      - dev
      - main
    tags:
      - '*.*.*'  # Se activará también si hay un push de un tag git

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      run: |
        IMAGE_NAME="ghcr.io/${{ github.repository }}:"


        if [[ "${GITHUB_REF}" == "refs/heads/dev" ]]; then
          TAG="latest"
        elif [[ "${GITHUB_REF}" == "refs/heads/main" ]]; then
          TAG="release"
        elif [[ "${GITHUB_REF}" == refs/tags/* ]]; then
            TAG="${GITHUB_REF#refs/tags/}"
        fi

        docker build -t ${IMAGE_NAME}${TAG} .
        docker push ${IMAGE_NAME}${TAG}
